### ISSUE TITLE
Method for listing subentities of a given CellType

### ISSUE THREAD

**Issue by presheaf** [MiroK/FEliX.jl#1]
I am currently working on methods init_facets!() and init_connectivity!() for GenericMesh. Currently, cells has a CellType, but are stored only as tuples of their vertex indices (unless I miss something). As such, there needs to be a CellType-specific method subentities(D, type). In my mind it should return a list of the dimension D subentities of some "reference" CellType, so that subentities(1, Quad) = [(1, 2), (2, 3), (3, 4), (4, 1)]. This could then be used by init_facets!() to generate a list of all facets in the mesh so they can be numbered.

My question is twofold - does this already exist or is there a better way of doing it? If not, I can get on adding it.

**Comment by MiroK** [comment]
No, there isn't `subentities(type, D)` method. I think adding it to `CellType` is a good choice and so is the returned value. One thing to keep in mind is that at some point we might want curved elements, e.g a quadratic triangle has then facets defined by 3 nodes. We could do the numbering now, e.g. similar to [gmsh](http://gmsh.info/doc/texinfo/gmsh.html#MSH-ASCII-file-format) or FEniCS (numbering of dofs in tri/tets). Or we can simplify and only implement `CellType{T, G, 1, F}`. I would do the [latter](https://en.wikipedia.org/wiki/KISS_principle), but you decide.

**Comment by mikaem** [comment]
Are we doing this as much as possible like Fenics, but with added dimension due to possibly curved cells? I like this paper as a resource: http://scholar.google.no/scholar_url?url=https://arxiv.org/pdf/1205.3081&hl=no&sa=X&scisig=AAGBfm2ApL1AWQt5G3CJtl46cP_Kwdm5GQ&nossl=1&oi=scholarr&ved=0ahUKEwiBsf2oqPfSAhUjOJoKHZuOBzIQgAMICSgAMAA

M

27. mar. 2017 8:18 p.m. skrev Miroslav Kuchta <notifications@github.com>:

No, there isn't subentities(type, D) method. I think adding it to CellType is a good choice and so is the returned value. One thing to keep in mind is that at some point we might want curved elements, e.g a quadratic triangle has then facets defined by 3 nodes. We could do the numbering now, e.g. similar to gmsh<http://gmsh.info/doc/texinfo/gmsh.html#MSH-ASCII-file-format> or FEniCS (numbering of dofs in tri/tets). Or we can simplify and only implement CellType{T, G, 1, F}. I would do the latter<https://en.wikipedia.org/wiki/KISS_principle>, but you decide.

**Comment by MiroK** [comment]
Yes, curved elements (`D>1`) should be an option but there should also be room for elements like pyramids (`F` not a `:simplex` or `:cube`). In addition, the mesh could consist of different element types, e.g. [here](https://github.com/MiroK/FEliX.jl/blob/master/src/mesh/mesh.jl#L46) I tried to be general.

**Comment by kent-and** [comment]
Curvature may not change connectivety. Connectivity may be defined in terms
of cells, verticies even on curved elements. Hanging nodes, h-p may be a
different story.
